// Guion del showcase: textos del panel, tips y tiempos de cada paso.
// Todo el video sale de aquí: cambia un texto o un tiempo y vuelve a renderizar.
window.GUION = {
  inicioPasos: 6.5,   // segundo en que arranca el paso 1
  duracionPaso: 5.4,  // segundos por paso
  capitulos: [
    { nombre: 'Inicio', pasos: [1] },
    { nombre: 'Identidad', pasos: [2, 3, 4, 5, 6] },
    { nombre: 'Tus datos', pasos: [7, 8, 9] },
    { nombre: 'Agencia', pasos: [10] },
    { nombre: '¡Listo!', pasos: [11, 12] },
  ],
  pasos: [
    { kicker: 'Inicio', titulo: 'Abre la App Ficensa',
      texto: 'En la pantalla de inicio, toca el botón circular <b>“Abrir cuenta”</b>.',
      tip: 'Ten tu DNI a mano antes de empezar: lo usarás en los siguientes pasos.' },
    { kicker: 'Verifica tu identidad', titulo: 'Lee las instrucciones',
      texto: 'Revisa los consejos para capturar tu DNI y presiona <b>“Continuar”</b>.',
      tip: 'Busca un lugar con buena luz y coloca tu DNI sobre una superficie oscura.' },
    { kicker: 'Verifica tu identidad', titulo: 'Captura el frente del DNI',
      texto: 'Encuadra el frente de tu DNI dentro del recuadro y presiona <b>“Tomar foto”</b>.',
      tip: 'Evita el flash y los reflejos: todos los datos deben leerse con claridad.' },
    { kicker: 'Verifica tu identidad', titulo: 'Validación automática',
      texto: 'La app revisa tu imagen. Cuando aparece el <b>ícono verde</b>, todo está en orden.',
      tip: 'Mantén la app abierta mientras valida; toma solo unos segundos.' },
    { kicker: 'Verifica tu identidad', titulo: 'Captura el reverso',
      texto: 'Ahora encuadra la <b>parte posterior</b> de tu DNI y presiona <b>“Tomar foto”</b>.',
      tip: 'Asegúrate de que el código de barras se vea completo y nítido.' },
    { kicker: 'Verifica tu identidad', titulo: 'Prueba de vida',
      texto: 'Sigue las indicaciones en pantalla y <b>gira tu rostro</b> cuando la app te lo pida.',
      tip: 'Retira lentes, gorra o mascarilla y mueve la cabeza despacio.' },
    { kicker: 'Tus datos', titulo: 'Datos de contacto',
      texto: 'Ingresa tu número móvil <b>(+504)</b> y tu correo electrónico.',
      tip: 'Usa un número y un correo activos: ahí recibirás tu código y tus credenciales.' },
    { kicker: 'Tus datos', titulo: 'Código de verificación',
      texto: 'Escribe el <b>código OTP</b> que te enviamos y presiona <b>“Continuar”</b>.',
      tip: 'El código dura solo un minuto: tenlo a mano antes de que expire.' },
    { kicker: 'Tus datos', titulo: 'Datos',
      texto: 'Completa los datos que te pide la app, como tu <b>municipio</b> y tu dirección de residencia.',
      tip: 'Agrega un punto de referencia para ubicar tu dirección con facilidad.' },
    { kicker: 'Tu tarjeta de débito', titulo: 'Elige tu agencia',
      texto: 'Selecciona la agencia donde quieres <b>retirar tu tarjeta de débito</b> y presiona <b>“Solicitar”</b>.',
      tip: 'Elige la agencia que te quede más cerca para retirar tu tarjeta.' },
    { kicker: '¡Casi listo!', titulo: 'Banca en Línea',
      texto: 'Te enviamos al correo tus <b>credenciales temporales</b> para ingresar a Banca en Línea.',
      tip: 'Revisa también la carpeta de spam o correo no deseado.' },
    { kicker: '¡Listo!', titulo: 'Cuenta creada',
      texto: 'Verás la confirmación final. Presiona <b>“Cerrar”</b> y ¡bienvenido a Banco Ficensa!',
      tip: '¿Tienes dudas? Comunícate con nuestro Call Center.' },
  ],
  // Datos de ejemplo que se escriben en la app (ficticios)
  datos: {
    usuario: 'JLOPEZ08',
    nombre: 'JOSÉ ANTONIO LÓPEZ',
    dni: '0801-1990-12345',
    telefono: '9876-5432',
    correo: 'jlopez@correo.com',
    otp: '482913',
    municipio: 'Tegucigalpa',
    direccion: 'Col. Palmira, calle principal',
    referencia: 'Frente al parque',
    barrio: 'Palmira',
    agencias: ['Oficina Principal Tegucigalpa', 'Agencia Boulevard Morazán', 'Agencia Kennedy', 'Agencia Comayagüela'],
  },
  intro: { titulo: ['Abre', 'tu', 'cuenta', 'desde', 'tu', 'celular'], sub: 'Te mostramos cómo, paso a paso',
    chips: ['12 pasos', 'Verificación biométrica', 'Desde la App Ficensa'] },
  cierre: { titulo: '¡Así de fácil!', sub: 'Abre tu cuenta hoy desde la App Banco Ficensa',
    lista: ['Verifica tu identidad', 'Completa tus datos', 'Elige dónde retirar tu tarjeta'],
    cta: 'Descarga la App y abre tu cuenta hoy', nota: 'Disponible en tu tienda de aplicaciones' },
  // Versión corta (~36 s): 6 momentos clave, intro y cierre más ágiles. "pantalla" es la pantalla de la app (1 a 12).
  versiones: {
    corta: {
      inicioPasos: 4.4, duracionPaso: 4.3, cierre: .62,
      capitulos: [
        { nombre: 'Inicio', pasos: [1] },
        { nombre: 'Identidad', pasos: [2, 3] },
        { nombre: 'Tus datos', pasos: [4] },
        { nombre: 'Agencia', pasos: [5] },
        { nombre: '¡Listo!', pasos: [6] },
      ],
      pasos: [
        { pantalla: 1, kicker: 'Inicio', titulo: 'Abre la App Ficensa',
          texto: 'Toca el botón <b>“Abrir cuenta”</b> en la pantalla de inicio.',
          tip: 'Ten tu DNI a mano antes de empezar.' },
        { pantalla: 3, kicker: 'Verifica tu identidad', titulo: 'Fotografía tu DNI',
          texto: 'Captura el <b>frente y el reverso</b> de tu DNI dentro del recuadro.',
          tip: 'Usa buena luz, un fondo oscuro y evita el flash.' },
        { pantalla: 6, kicker: 'Verifica tu identidad', titulo: 'Prueba de vida',
          texto: '<b>Gira tu rostro</b> cuando la app te lo pida para confirmar que eres tú.',
          tip: 'Retira lentes, gorra o mascarilla.' },
        { pantalla: 7, kicker: 'Tus datos', titulo: 'Completa tus datos',
          texto: 'Ingresa tu móvil, tu correo y tu dirección, y confirma con el <b>código OTP</b>.',
          tip: 'El código dura solo un minuto: tenlo a mano.' },
        { pantalla: 10, kicker: 'Tu tarjeta de débito', titulo: 'Elige tu agencia',
          texto: 'Selecciona la agencia donde quieres <b>retirar tu tarjeta de débito</b>.',
          tip: 'Elige la que te quede más cerca para retirarla.' },
        { pantalla: 12, kicker: '¡Listo!', titulo: 'Cuenta creada',
          texto: 'Recibirás en tu correo tus <b>credenciales temporales</b> de Banca en Línea.',
          tip: '¿Tienes dudas? Comunícate con nuestro Call Center.' },
      ],
    },
  },
};
